// Auto-generated by scripts/generate-blurs.mjs — do not edit by hand.

export const blurs: Readonly<Record<string, string>> = {
  "/1.webp": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAABQAgCdASoMAAcAA8BgJbACdH8AGJT7lOWj/ogA/s91RG1i220G25YM9w7CgxyIZQBPA6SCC9kbm60WC4HNSv5JkQqwUq+TySbM/9iHXe/Jv1kPFwAAAA==",
  "/2.webp": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoMAAcAA8BgJYwCsADdOm25sAD++FYZGLQnpGdOT4gqLMwKT/aiCDz0NBtL10DpdoaO9NVKEeAAAA==",
  "/3.webp": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoMAAwAA8BgJZQC7AD0PEuxnTsAAP73gmXyBmXXrUd+HXWNke95/uE28wnyvtx40CRKIY/VQwqoaB816IJ0nNb5SiTEg2AA",
  "/4.webp": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoMAAwAA8BgJaACdAEfRfHfnwZAAP7okalv+PhkRPLJJAEDPKi2j55a18rijzuBLr1rLnrRhdQnsMjDThI1/ligydctSIyzcr6g5EkAAAA=",
  "/main.webp": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABQAgCdASoMAAwAA8BgJZgCdAYstnMqw5inOgAA/vaTfb47KN5g/OsPa6yey3m1NYh+ZaFbHuiKxnCm4MPhEU+UG4jQflIBOyDu62FuTTzw+o0FSNsTJjvYZetCNAAA",
};

export function blurFor(src: string): string | undefined {
  return blurs[src];
}
