// Generate base64 blur placeholders for every public image and emit
// a TypeScript module the app can import.
//
//   node scripts/generate-blurs.mjs
//
// Output: src/lib/blurs.ts — a typed map keyed by `/file.webp` path.

import { readdir, writeFile, stat } from "node:fs/promises";
import { join, extname, basename } from "node:path";
import sharp from "sharp";

const ROOT = process.cwd();
const publicDir = join(ROOT, "public");
const outFile = join(ROOT, "src", "lib", "blurs.ts");

const supported = new Set([".webp", ".jpg", ".jpeg", ".png", ".avif"]);

const files = await readdir(publicDir);
const entries = [];

for (const file of files) {
  const ext = extname(file).toLowerCase();
  if (!supported.has(ext)) continue;
  const filePath = join(publicDir, file);
  const s = await stat(filePath);
  if (!s.isFile()) continue;

  const blurBuffer = await sharp(filePath)
    .resize(12, 12, { fit: "inside" })
    .webp({ quality: 35 })
    .toBuffer();
  const dataUrl = `data:image/webp;base64,${blurBuffer.toString("base64")}`;

  // Strip extension neutralization — store under the original path.
  entries.push([`/${file}`, dataUrl]);
  console.log(`${file.padEnd(20)} ${(blurBuffer.length).toString().padStart(5)} bytes blur`);
}

entries.sort(([a], [b]) => a.localeCompare(b));

const ts =
  `// Auto-generated by scripts/generate-blurs.mjs — do not edit by hand.\n\n` +
  `export const blurs: Readonly<Record<string, string>> = {\n` +
  entries.map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join("\n") +
  "\n};\n\n" +
  `export function blurFor(src: string): string | undefined {\n` +
  `  return blurs[src];\n` +
  `}\n`;

await writeFile(outFile, ts, "utf8");
console.log(`\nWrote ${entries.length} blur entries to ${outFile}`);

void basename;
